export const ADD_SCORE_REQUEST = 'ADD_SCORE_REQUEST'
export const ADD_SCORE_SUCCESS = 'ADD_SCORE_SUCCESS'
export const ADD_SCORE_FAIL = 'ADD_SCORE_FAIL'

export const LIST_MY_GAMES_REQUEST = 'LIST_MY_GAMES_REQUEST'
export const LIST_MY_GAMES_SUCCESS = 'LIST_MY_GAMES_SUCCESS'
export const LIST_MY_GAMES_FAIL = 'LIST_MY_GAMES_FAIL'
export const LIST_MY_GAMES_RESET = 'LIST_MY_GAMES_RESET'

export const SCORE_DELETE_REQUEST = 'SCORE_DELETE_REQUEST'
export const SCORE_DELETE_SUCCESS = 'SCORE_DELETE_SUCCESS'
export const SCORE_DELETE_FAIL = 'SCORE_DELETE_FAIL'

export const SCORE_ALL_DELETE_REQUEST = 'SCORE_ALL_DELETE_REQUEST'
export const SCORE_ALL_DELETE_SUCCESS = 'SCORE_ALL_DELETE_SUCCESS'
export const SCORE_ALL_DELETE_FAIL = 'SCORE_ALL_DELETE_FAIL'
